void Drive (float inches, int velocityPct, bool doWaitForFinished, int unitType = 0);
void autoStrafe(float inches, int velocityPct, bool doWaitForFinished, int unitType = 0);
void autoBackLiftHold (float liftDegrees, int liftVelocity, bool doWaitForFinished);
void smoothTurn (float turnDegrees, int maxTurnSpeed, vex::inertial& imu);
void smootherTurn (float turnDegrees, int maxTurnSpeed, vex::inertial& imu);
void smoothererTurn (vex::inertial& imu);
void autoTurn (float turnDegrees, int velocityPct, char bothSides, vex::inertial& imu);
void badAutoTurn (int turnDegrees, int velocityPct, int bothSides, bool doWaitForFinished);
void autoFrontLift (float liftDegrees, int liftVelocity, bool doWaitForFinished, bool doHold, int goTopOrBottom = 0);
//void autonSpinnyThing (int turnDegrees, int turnVelocity, bool doWaitForFinished, int openOrClosed = 0);
void autoBackLift (float liftDegrees, int liftVelocity, bool doWaitForFinished, bool doHold, int doTopOrBottom = 0);
void autoBackLiftRevs (float liftRevolutions, int liftVelocity, bool doWaitForFinished, bool doHold, int toTopOrBottom = 0);
void autonRingLiftOn(int velocityPct, bool ringLiftForward);
void autonRingLiftOff();
void smoothDrive(float inches, float startSpeed);
void autonLowerRingLift(bool doWaitForFinished);
void autonRaiseRingLift(bool doWaitForFinished);
void autonLatchClose(bool doWaitForFinished);
void autonLatchOpen(bool doWaitForFinished);
void driving(float inches, float turnVelocity, bool doWaitForFinished);